export const projectsData = [
  {
    title: "bfTattoo",
    title1: "bf  ",
    title2: "Tattoo ",
    src: "poza.jpg",
    color: "#000000",
    identifier: "work",
  },
  {
    title: "SapeClasice",
    title1: "Şape ",
    title2: "Clasice",
    src: "poza.jpg",
    color: "#8C8C8C",
    identifier: "work",
  },
  {
    title: "GreekGods",
    title1: "Greek",
    title2: "Gods",
    src: "poza.jpg",
    color: "#EFE8D3",
    identifier: "project",
  },
  {
    title: "BallRun",
    title1: "Ball ",
    title2: "Run",
    src: "poza.jpg",
    color: "#706D63",
    identifier: "project",
  },
  {
    title: "Pokedex",
    title1: "Poke",
    title2: "dex",
    src: "poza.jpg",
    color: "#706D63",
    identifier: "project",
  },
  {
    title: "TicTacToe",
    title1: "Tic Tac",
    title2: "Toe",
    src: "poza.jpg",
    color: "#706D63",
    identifier: "project",
  },
  {
    title: "PlanetFacts",
    title1: "Planet ",
    title2: "Facts",
    src: "poza.jpg",
    color: "#706D63",
    identifier: "project",
  },
  {
    title: "CartoonNetwork",
    title1: "Cartoon",
    title2: "Network",
    src: "poza.jpg",
    color: "#706D63",
    identifier: "project",
  },
];
