export const projectsData = [
  {
    title: "bfTattoo",
    titleFull: "bf Tattoo  ",
    src: "poza.jpg",
    color: "#000000",
    identifier: "work",
    contribution: "Development",
  },
  {
    title: "SapeClasice",
    titleFull: "Şape Clasice ",
    src: "poza.jpg",
    color: "#8C8C8C",
    identifier: "work",
    contribution: "Design & Development",
  },
  {
    title: "GreekGods",
    titleFull: "Greek Gods",
    src: "poza.jpg",
    color: "#EFE8D3",
    identifier: "project",
    contribution: "Design & Development",
  },
  {
    title: "BallRun",
    titleFull: "Ball Run",
    src: "poza.jpg",
    color: "#706D63",
    identifier: "project",
    contribution: "Bruno Simon course",
  },
  {
    title: "Pokedex",
    titleFull: "Pokedex",
    src: "poza.jpg",
    color: "#706D63",
    identifier: "project",
    contribution: "Design & Development",
  },
  {
    title: "TicTacToe",
    titleFull: "Tic Tac Toe",
    src: "poza.jpg",
    color: "#706D63",
    identifier: "project",
    contribution: "Development",
  },
  {
    title: "PlanetFacts",
    titleFull: "Planet Facts ",

    src: "poza.jpg",
    color: "#706D63",
    identifier: "project",
    contribution: "Development",
  },
  {
    title: "CartoonNetwork",
    titleFull: "Cartoon Network",
    src: "poza.jpg",
    color: "#706D63",
    identifier: "project",
    contribution: "Development",
  },
];
